### ISSUE TITLE
mappings.go contains an internal reference, failing to compile

### ISSUE THREAD

**Issue by tonjo** [go-sourcemap/sourcemap#12]
When trying to `go build`:

    mappings.go:8:2: use of internal package not allowed

The line to blame is in import:

    "github.com/go-sourcemap/sourcemap/internal/base64vlq"

**Comment by vmihailenco** [comment]
Make sure you clone code into $GOPATH/src/github.com/go-sourcemap/sourcemap or use go get. The problem is in your setup, not this package.

**Comment by tonjo** [comment]
Seems like an import problem when referenced by other packages.
Not a go expert, sorry.
